<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_main-content</name>
   <tag></tag>
   <elementGuidId>19fffa7d-08c3-4016-bf2e-401e4500c51d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'main-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#main-content</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>76bd8a1e-47a1-4261-b12c-bb1f7389c2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main-content</value>
      <webElementGuid>e0e9d5cd-4df4-4b5e-9830-0bcf0739b3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section hero</value>
      <webElementGuid>bab4022c-9d9d-480c-9b83-6064542aeb78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>main-content</value>
      <webElementGuid>1ccf6f23-2d78-4bf0-a99a-af2379ad0f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>4169690f-0d28-4d07-8d89-8051f2bb8e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-655b66cc693e7c78c58d4ebcea417928</value>
      <webElementGuid>3b7b7df7-6c38-454b-94f6-5ea41b39ba0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'main-content']</value>
      <webElementGuid>61f34826-ee17-4cda-8121-800450c734ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'main-content']</value>
      <webElementGuid>8fd0fcee-af95-4205-966e-f73ce16adc6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[@id = 'main-content' and (text() = 'main-content' or . = 'main-content')]</value>
      <webElementGuid>dbe51591-96b2-41d2-a859-12a0b6347aa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
